# This file was generated by GoReleaser. DO NOT EDIT.
cask "sneat" do
  version "0.10.2"

  on_macos do
    on_arm do
      sha256 "1f100103fb4d411d9b62fd0786578124679695cb3b234cfe33804f0a5d2665e4"
      url "https://github.com/sneat-co/sneat-cli/releases/download/v#{version}/sneat_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0f763a6608c5d03f70b1879ab328c6f4192816185997f9feab20b13f227cc9bd"
      url "https://github.com/sneat-co/sneat-cli/releases/download/v#{version}/sneat_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "93cc634429afced495fa0ef955f29f4059afc08a5649e1b89c3533fd91aeb012"
      url "https://github.com/sneat-co/sneat-cli/releases/download/v#{version}/sneat_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8ba0133dc7c62679d572e15a7c8c542eabbb174e064d4584b381eb2a299ea7a5"
      url "https://github.com/sneat-co/sneat-cli/releases/download/v#{version}/sneat_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sneat"
  desc "sneat - Text-based User Interface for Sneat.app"
  homepage "https://sneat.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sneat"

  # No zap stanza required
end
