# This file was generated by GoReleaser. DO NOT EDIT.
cask "sneat" do
  version "0.5.1"

  on_macos do
    on_arm do
      sha256 "2318ee64fa554887adccff259bd6fb611a456f80fe083ef74cfe248cb3f8c31c"
      url "https://github.com/sneat-co/sneat-cli/releases/download/v#{version}/sneat_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "baa82208266acae5447aba7207525d27b04240cbb0fb7a8b9922390c7f35d201"
      url "https://github.com/sneat-co/sneat-cli/releases/download/v#{version}/sneat_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "eb036164e68953c9050b459635b9a9de5081816257264703c9f579bc1ca94044"
      url "https://github.com/sneat-co/sneat-cli/releases/download/v#{version}/sneat_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "640a7680fbef2a8d4d33184df17dd49590ebe1a9c2926505833e90757b482adc"
      url "https://github.com/sneat-co/sneat-cli/releases/download/v#{version}/sneat_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sneat"
  desc "sneat - Text-based User Interface for Sneat.app"
  homepage "https://sneat.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sneat"

  # No zap stanza required
end
