# This file was generated by GoReleaser. DO NOT EDIT.
cask "sneat" do
  version "0.6.1"

  on_macos do
    on_arm do
      sha256 "16fe2b1726e902021104b0e5aa08b7147c96fa0be1caadcb772f22aa35636c67"
      url "https://github.com/sneat-co/sneat-cli/releases/download/v#{version}/sneat_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4094912ab529c764da5816563bd3f53a07c7a41fe687933767758b8a9143ed75"
      url "https://github.com/sneat-co/sneat-cli/releases/download/v#{version}/sneat_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "289d7cbd10aee8fa6a32c062e5eb81d8c88e115321d5eb1a2f8c546cc93ca481"
      url "https://github.com/sneat-co/sneat-cli/releases/download/v#{version}/sneat_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "82c76aae5f26f0d3537c7fdc2312b95c77b209a20525af5fcc061374225d017c"
      url "https://github.com/sneat-co/sneat-cli/releases/download/v#{version}/sneat_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sneat"
  desc "sneat - Text-based User Interface for Sneat.app"
  homepage "https://sneat.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sneat"

  # No zap stanza required
end
